services:
  app:
    image: none
    container_name: notice-app
    build: # 로컬 환경에서는 빌드 옵션을 활성화
      context: .
      dockerfile: App.Dockerfile
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local  # 로컬 프로파일 활성화 (Spring용)
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=notice
      - SPRING_DATA_MONGODB_USERNAME=srunners  # 초기화된 사용자 계정
      - SPRING_DATA_MONGODB_PASSWORD=srunners  # 초기화된 사용자 비밀번호

  mongo:
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: mongodb
    ports:
      - "27017:27017" # 외부에서 접근하려면 열어둠
    volumes:
      - /mnt/c/dev/srunners/mongo-data:/data/db  # MongoDB 데이터 영구 저장