server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notice
      username: srunners
      password: srunners
  mail:
    host: smtp.gmail.com
    port: 587
    username: srunners.owner@gmail.com
    password: ufvgzmkvmwtrhwpr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

logging:
  level:
    org.springframework.mail: DEBUG