name: CD - Deploy to GCP VM

# 파이프라인 실행 조건: CI 워크플로우가 완료되었을 때 실행
on:
  workflow_run:
    workflows:
      - CI - Build and Push Docker Image # CI 단계가 성공적으로 완료되어야 실행
    types:
      - completed
  workflow_dispatch:

# 환경 변수 정의
env:
  REGISTRY: ghcr.io

jobs:
  deploy-to-gcp:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      # Step 1: 소문자 변환된 이미지 이름 설정
      - name: Set Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${OWNER,,}/${REPO,,}" >> ${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

      # Step 2: GCP VM에 SSH 연결 및 Docker 이미지 배포
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.GCP_SSH_PASSPHRASE }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker stop notice-service || true
            docker rm notice-service || true
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker run -d --name notice-service -p 80:8080 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest